version: '3.4'

services:
  exchange_service:
    image: exchange_service
    build:
      context: ./exchange_service
      dockerfile: Dockerfile
    hostname: localhost
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq:3.8.0-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
  log-consumer:
    image: log-consumer
    build:
      context: ./log_consumer
      dockerfile: Dockerfile
    hostname: localhost
    depends_on:
      - rabbitmq
    ports:
      - "8081:8081"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_QUEUE=logs