name: Workflow for push event
on:
  push:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          only-new-issues: true
  unit-test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: Run unit & integration tests
        run: go test ./exchange_service/test/unit/...
  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: Run e2e tests
        run: go test ./exchange_service/test/e2e
  architecture-test:
    name: Architecture Test
    runs-on: ubuntu-latest
    needs: [e2e-test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: Run architecture tests
        run: go test ./exchange_service/test/architecture
